source 'http://rubygems.org'

gem 'rails', '3.0.0.beta2'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'


gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'mysql', '>= 2.8.1'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri', '1.4.1'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Use RSpec for unit testing.
group :test do
  gem 'rspec', '>= 2.0.0.a'
  gem 'rspec-rails', '>= 2.0.0.a'
end

# Use Cucumber with Capybara for integration testing.
group :test do
  gem 'capybara'
  # The slimmed down version of test-unit in Ruby 1.9.1 isn’t enough for
  # Cucumber.
  gem 'test-unit'
  gem 'cucumber'
  gem 'cucumber-rails', :git => 'git://github.com/aslakhellesoy/cucumber-rails.git'
end


